url: "https://betweenourworlds.org"
baseurl: ""
webid: "https://betweenourworlds.org/#org"
datadumpurl: "https://datadump.betweenourworlds.org"
tpfurl: "https://data.betweenourworlds.org"
description: "Between Our Worlds is an initiative to provide metadata information about anime as Linked Open Data."

permalink: pretty
markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass
