url: "https://betweenourworlds.org"
baseurl: ""
webid: "https://betweenourworlds.org/#org"
datadumpurl: "https://datadump.betweenourworlds.org"
tpfurl: "https://data.betweenourworlds.org"

permalink: pretty
markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass
